name: Build Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        uses: hluwa/Theos-Action@main

      - name: Build
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./packages/*.deb
